web_server_location      = "westus2"
web_server_rg            = "web-rg"
resource_prefix          = "web-server"
web_server_address_space = "10.0.0.0/22"
web_server_address_prefix= "10.0.1.0/24"
web_server_name           = "web"
environment               = "Dev"
web_server_count          = 2
#web_server_subnets        = ["10.0.1.0/24","10.0.2.0/24"]